#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "outline-server "
name = "Outline Server "

description.en = "Proxy server that runs a Shadowsocks instance"
description.fr = "Serveur proxy qui exécute une instance Shadowsocks"

version = "1.10.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://www.getoutline.org/"

code = "https://github.com/Jigsaw-Code/outline-server"

[integration]
yunohost = '>= 11.2.30'
helpers_version = "2.1"
architectures = "all" 
multi_instance = true
ldap = "false" 
sso = "false"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Jigsaw-Code/outline-server/archive/refs/tags/server-v1.10.1.tar.gz"
        sha256 = "0968d8e066bc7996c99c8e68930b8cf514543d529e348b4a8c0a01c888f4e5ee"

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
