#!/bin/bash
### App file generated with YoloGen, the Yunohost app generator, version .

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install
ynh_go_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's configuration file..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
  ynh_exec_as_app npm install
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting app's systemd service..."

ynh_systemd_action --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"